// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRLvWq1qXSDPv0Ywd2P_WI4vwVdDarMMg',
    appId: '1:350157611272:web:1ad28ed15fb451959a0cbd',
    messagingSenderId: '350157611272',
    projectId: 'reaktor-issues-test',
    authDomain: 'reaktor-issues-test.firebaseapp.com',
    storageBucket: 'reaktor-issues-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBho7hNq3uDNZVP_AMjQ8vhMjcQHXntrak',
    appId: '1:350157611272:android:f85ddeca380571e39a0cbd',
    messagingSenderId: '350157611272',
    projectId: 'reaktor-issues-test',
    storageBucket: 'reaktor-issues-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeKdYxG2xUYGnFDYvpk8XMt6Trz83PVMY',
    appId: '1:350157611272:ios:ddf1e773f67aa16a9a0cbd',
    messagingSenderId: '350157611272',
    projectId: 'reaktor-issues-test',
    storageBucket: 'reaktor-issues-test.firebasestorage.app',
    iosClientId: '350157611272-1jjk3alr9fkeeve48938nlkv0gkd86sd.apps.googleusercontent.com',
    iosBundleId: 'com.example.reaktorIssuesFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeKdYxG2xUYGnFDYvpk8XMt6Trz83PVMY',
    appId: '1:350157611272:ios:ddf1e773f67aa16a9a0cbd',
    messagingSenderId: '350157611272',
    projectId: 'reaktor-issues-test',
    storageBucket: 'reaktor-issues-test.firebasestorage.app',
    iosClientId: '350157611272-1jjk3alr9fkeeve48938nlkv0gkd86sd.apps.googleusercontent.com',
    iosBundleId: 'com.example.reaktorIssuesFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRLvWq1qXSDPv0Ywd2P_WI4vwVdDarMMg',
    appId: '1:350157611272:web:514c39d50e47986c9a0cbd',
    messagingSenderId: '350157611272',
    projectId: 'reaktor-issues-test',
    authDomain: 'reaktor-issues-test.firebaseapp.com',
    storageBucket: 'reaktor-issues-test.firebasestorage.app',
  );
}
